import { createSlice } from "@reduxjs/toolkit";
import { Search } from "lucide-react";
import { act } from "react";
const initialState = {
    companies: [], // Array of companies
    searchText: '' // Text used for filtering companies
  };
const CompanySlice = createSlice({
    name: "company",
    initialState: {
        singleCompany: null,
        companies:[],
        SearchCompanyByText:"",
    },
    reducers: {
        // actions
        setSingleCompany: (state, action) => {
            state.singleCompany = action.payload;
        },
        setCompanies:(state , action) =>{
            state.companies =action.payload ;
        },
        SearchCompanyByText(state, action) {
            state.searchText = action.payload; // Update searchText with the input value
          }
    },
});

// Exporting the actions generated by createSlice
export const { setSingleCompany , setCompanies , SearchCompanyByText } = CompanySlice.actions;

// Exporting the reducer to be used in the store
export default CompanySlice.reducer;
